- cmd/custom.go
- cmd/test.go
- ibc/cosmos_chain.go
- ibc/test_chains.go
Adds `ibc-test-framework test custom` command, which allows complete customization of chain configurations for running tests.
Resolves #9
> Add test custom command

- ibc/relayerfactory.go
- ibc/test_setup.go
This provides more flexibility in supporting different relayer
configurations. It is the first step towards running relayer IBC tests
from a separate project.
> Extract RelayerFactory interface

- cmd/custom.go
- cmd/test.go
- ibc/chainfactory.go
- ibc/test_relay.go
- ibc/test_setup.go
- test/relayer_test.go
And provide two implementations to cover the test and custom commands.
Most importantly, this will allow future tests to choose to start more
than two chains, to eventually cover a single relayer process handling
more than one path.
> Extract ChainFactory interface

- chain/cosmos/chain_node.go
- ibctest/relayerfactory.go
- ibctest/test_setup.go
- relayer/rly/cosmos_relayer.go
- relayertest/test.go
- utils/docker.go
In places where we were passing (*testing.T).Name(), prefer to pass the
plain *testing.T value. This makes the interfaces more amenable to
external definitions that are also used specifically in Go tests.
This allows use of t.Cleanup rather than returning callbacks that need
to be deferred.
When we need to sanitize test names for containers, do it later in the
call chains.
> Make more code aware of *testing.T

- .github/CODEOWNERS
With the team settings, GitHub should now automatically pick a member of
the team to review changes to this repository.
> Add ibc-test-maintainers team to CODEOWNERS

- chain/cosmos/cosmos_chain.go
- ibc/Chain.go
- ibctest/test_setup.go
For non-docker relayers, we need to provide the host-bound rpc and gRPC
addresses. Those addresses cannot be determined until the chain
containers are up and running. The relayer does not have an existing API
to modify a chain's addresses, so delay relayer configuration until
after chains are running.
However, we need certain accounts set up to perform chain genesis, so
generate those keys out of band, provide the account details to genesis,
and then restore the keys into a new relayer setup.
> Support non-docker relayers

- Makefile
- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- cmd/ibctest/ibctest_test.go
- dockerutil/docker.go
- dockerutil/errors.go
- dockerutil/errors_test.go
- dockerutil/strings.go
- dockerutil/strings_test.go
- ibctest/test_setup.go
- relayer/rly/cosmos_relayer.go
- test/relayer_test.go
* Rename `utils` -> `dockerutil` to clarify the intention of that package. Seems like a safe name given every function in there is to help with docker related things. https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common
* Add unit test coverage for above package
* Update Makefile for unit tests
- NA
> refactor: Misc cleanup + unit test coverage

- ibctest/relayerfactory.go
- ibctest/test_setup.go
- relayer/rly/cosmos_relayer.go
First, these are not used by any existing RelayerFactory implementation.
Second, coupling relayer instances to a pair of chains will
overcomplicate upcoming many-chain relayer tests.
> Omit src and dst chains from RelayerFactory.Build

- dockerutil/strings.go
- dockerutil/strings_test.go
I kept seeing test with suffixes only composed of characters a, b, and
c. This was because it was only using the requested length for indexing
into the alphabet, and those tests were requesting a random string of
length 3.
> Fix indexing into alphabet for random characters

- ibctest/test_setup.go
The removed code is only referenced by the trophies directory, which is
currently not intended to compile. In fact, we are going to replace that
now out-of-date code with a simple text document referencing the fixed
issue.
> Remove some now-unused code

- relayertest/test.go
Ten blocks ought to be sufficient, but we are seeing test failures that
appear to stem from internal retries that don't finish quickly. Those
retries will be addressed separately in the relayer repository. In the
meantime, waiting for twenty blocks makes the tests a bit more forgiving
and reduces the frequency of CI retries.
> Wait for chains to produce more blocks in relayer tests

- chain/cosmos/cosmos_chain.go
- cmd/ibctest/example_matrix.json
- cmd/ibctest/ibctest_test.go
- ibctest/test_setup.go
- relayer/rly/cosmos_relayer.go
- test/relayer_test.go
- Run cleanup before and after
- Fix missing cleanup for rly docker `NodeJob`s
- Use latest images for example matrix. Keep fixed versions for CI
> Better docker cleanup

- Makefile
Docker on Mac can be finicky.
These commands usually do the trick.
> script: Add docker helper commands

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/penumbra/penumbra_chain.go
- chain/tendermint/tendermint.go
- chain/tendermint/tendermint_node.go
- chain/tendermint/tendermint_test.go
- ibc/Chain.go
- ibc/types.go
- ibctest/log.go
- log/iface.go
- log/log.go
- relayertest/test.go
Attempt to make meaningful assertions against IBC transactions and the followup acknowledgement transaction.
When `debug` logs activated, prints tendermint block details for cosmos chains.
* Bloats the `ibc.Chain` interface even more. 
* `WaitForBlocks` may be able to move toward `WaitForAck(seq uint64)` or similar. That may be explored in a future PR.
> feat: Assert IBC packet acknowledgments

- cmd/ibctest/ibctest_test.go
- ibctest/chainfactory.go
- ibctest/relayerfactory.go
- relayer/rly/cosmos_relayer.go
This moves the name generation logic into the factory, where it belongs,
instead of in the test generation logic.
This will also assist in producing additional reports about test
results.
> Add Name() method to relayer and chain factories

- README.md
- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- docs/logging.md
Vendor the style guide present in other Strangelove (SL) repos such as relayer and lens. The style guide has good guidelines so that we have consistent logging across different SL services.
I propose adding this style guide here unaltered.
*The following only presents alternatives. It is not a proposal (yet).*
I think style should be enforced by static analysis tools like linters, auto-formatters, or by other automated means. And those tools run on CI.
Otherwise, you run the risk of bikeshedding as developers critique code style back-and-forth in PRs. In my experience, such behavior has low business value.
Alternatively to linters, an interesting thought experiment would be creating a `strangelove/log` repo which wraps `zap`. All other Strangelove services use this internally maintained …
> docs: Add logging style guide

- cmd/ibctest/flags.go
- cmd/ibctest/ibctest_test.go
- relayertest/test.go
- testreporter/doc.go
- testreporter/messages.go
- testreporter/messages_test.go
- testreporter/reporter.go
- testreporter/reporter_test.go
This PR is the first step towards producing machine-readable test reports.
The `ibctest` executable now emits a report, defaulting to `~/.ibctest/reports/$UNIX_TIMESTAMP_NOW.json`, that is a file containing a stream of JSON objects representing test events that would be relevant to produce a human-readable report.
Internally, this introduces a `testreporter` package with a `*Reporter` type, which is used additively during plain Go tests to collect details at an individual test level in a machine-readable JSON format. See `testreporter/doc.go` for a thorough explanation of how to use the reporter.
As of this PR, the reporter tracks suite start and end times, and individual start/stop times along with skip and fail status -- which is roughly parity with the plain output from Go test. …
> Add initial test reporter

- relayertest/test.go
In attempting to test acknowledgements for `height timeout` and `timestamp timeout` scenarios, I discovered `timestamp` always passed and `height` always failed.
But what was really happening was `timestamp timeout` is not a capability of the go relayer `rly`. 
We were inadvertently omitting the test entirely. Therefore, unless you looked closely, it appears as if the test passes, when in fact, it wasn't run at all. 
This PR fixes the above issue, so you will explicity see `SKIP` in the test output like so:
> fix: Ensure skipped tests are not omitted

- ibc/Relayer.go
- ibctest/test_setup.go
- relayer/rly/cosmos_relayer.go
- relayertest/test.go
- testreporter/messages.go
- testreporter/messages_test.go
- testreporter/reporter.go
- testreporter/reporter_test.go
This was uniform to apply to all the one-off commands, but StartRelayer
and StopRelayer required a slightly different approach due to the
asynchronous style of starting the relayer in the background.
Now, container information, start and stop time, standard output and
standard error, for each relayer execution are included in the report,
so long as the ibc.Relayer implementation has implemented it.
> Add relayer executions to test report

- chain/cosmos/chain_node.go
- chain/tendermint/tendermint.go
- chain/tendermint/tendermint_test.go
If debug logging, pretty print Cosmos SDK transactions to trace the lifecycle of the chains. 
Previously, we were printing the Tendermint transactions which do not contain as much context or info.
* It's quite a bit of text to parse through but it's easier to follow than the previous implementation which would print raw bytes. 
* It's a lot of information so not practical to add as logging fields, imo. Events alone can be lots of data.
> feat(logging): Improved logging of cosmos sdk blocks and transactions

- .github/workflows/tests.yml
- README.md
- relayer/capability.go
- relayertest/test.go
- test_setup.go
- testreporter/messages.go
All comment and doc changes, except for the string ibc-test-framework
used in dynamic docker network names; changing that should have no
functional effect.
> Rename textual occurrences of ibc-test-framework

- chainfactory.go
- label/label.go
- relayerfactory.go
- relayertest/test.go
- testreporter/messages.go
- testreporter/messages_test.go
- testreporter/reporter.go
- testreporter/reporter_test.go
As of this change, labels are associated with individual tests and are
only used for reporting purposes. Filtering tests to run from the
command line is more complex than it might first appear, so that will
happen in a separate change. Label presence in test reports today could
be used for viewing a filtered subset of the report, however.
There are Relayer and Chain labels that are included with top-level
tests, and then individual subtests may have an optional set of labels.
> Add test labels

- chain/penumbra/penumbra_chain_test.go
- relayertest/test.go
- test_setup.go
SetupTestRun was slowing me down every time I needed to read through to
understand what it did.
It returned five values, of which three are not very special: the
context was a plain context.Background, the home directory was the
result of t.TempDir(), and a returned error was intended to always
result in a test failure.
The new ibctest.DockerSetup method returns a *dockertest.Pool and a
networkID value. Because it already accepted a *testing.T, any errors
during Docker setup will cause a call to t.Fatal to immediately fail the
test, as the test cannot continue without those Docker values.
The previously returned context and home directory are instead created
in the calling test where needed. I find this clearer.
This change also inlines the previously exported CreateNetwork function
which …
> Replace ibctest.SetupTestRun with ibctest.DockerSetup

- chainset.go
- relayertest/test.go
- test_setup.go
The StartChainsAndRelayerFromFactory function, which has now been
renamed to StartChainPairAndRelayer, had some lengthy sections to set up
chains in preparation for tests. The logic in those sections would apply
just the same to three or more chains. We are working towards supporting
tests beyond a single pair of chains, so extract that common behavior
into the new chainSet type.
The chainSet type is unexported for now, as it contains behavior that
was internal to the StartChainsAndRelayerFromFactory function.
> Extract ibctest.chainSet type to simplify future tests

- README.md
- chainfactory.go
- cmd/ibctest/ibctest_test.go
- relayertest/test.go
The old way was ROOT/$relayer/$chains/$subtests. The new organization is
ROOT/$arity/$chains/$relayer/$subtests.
In the new layout, $arity currently has one possible value, "pairs".
Although we have discussed the possibility of supporting "triplets" as
an arity, it is not currently on the roadmap for compliance tests.
Leaving arity as part of the test hierarchy keeps that option open
without incurring a command-line API change. (We could also have IBC
configuration tests against a single chain, if that need arises.)
Also of note, this organizes $chains before $relayer. I think this is
more in the spirit of what ibctest is providing. The previous layout was
asking the question, "Does relayer X properly relay for chains A and B,
and for chains C and D?" The new layout asks, "For chains A …
> Reorganize test hierarchy

- cmd/ibctest/ibctest_test.go
- conformance/test.go
The new name is more accurate because it is testing not only the
relayer, but the interaction of other chains involved too.
> Rename relayertest package to conformance

- chainset.go
- ibc/Relayer.go
- interchain.go
- relayer/rly/cosmos_relayer.go
- relayerfactory.go
- test_setup.go
- test_user.go
- world.go
This PR adds the `Interchain`type, which provides a Builder-pattern interface for constructing a network of arbitrary Chains and Relayers with user-controlled relaying paths.
We only have a single use of the type in `ibctest.StartChainPairAndRelayer` so far, but we will continue to use the type as the set of tests expand; and we will maintain this as an exported API so that other projects can trivially construct interchain definitions for IBC testing.
> Initial implementation of ibctest.Interchain

- chain/cosmos/chain_node.go
- chain/cosmos/codec.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/query.go
- chain/penumbra/penumbra_chain.go
- conformance/test.go
- go.mod
- ibc/chain.go
- ibc/packet.go
- ibc/packet_test.go
- ibc/types.go
- test/poll_for_state.go
- test/poll_for_state_test.go
- test/wait_for_blocks.go
Further solidifies the pattern to make `ibc.Chain` simple. Essentially, query some state from the chain; other functions poll, wait, or take other action on the state.
The (hopefully quick) upcoming PR is polling for timeouts. 
Timeouts was not included in this PR because it was already sizable.
The hope is polling for state may improve test suite run times.
* I could not reduce the `ibc.Chain` interface. I explored a few designs (even with generics) but having 2 separate methods for acks and timeouts will probably be easiest. 
* Reminder: The package `test` is a "sibling" package and probably not the right place. I'd prefer the root `ibctest`, but an import cycle currently prevents it. It's not worth fighting the import cycle yet.
> feat: Poll for packet acknowledgements

- .gitignore
- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/penumbra/penumbra_chain.go
- dockerutil/errors.go
- go.mod
- ibc/Relayer.go
- ibc/chain.go
- ibc/types.go
- relayer/rly/cosmos_relayer.go
- test_chains.go
This PR adds the necessary types and functionality that should be required to support testing interchain accounts.
This PR *does not* add testing scenarios that simulate the usage of interchain accounts.
Added methods to the `Chain` interface for registering an interchain account, querying an interchain account, and sending a bank transfer message to an interchain account.
Added methods for creating clients, creating connections, and querying connections to the `Relayer` interface.
Added a test chain that will utilize a docker image for the binary from the interchain accounts [demo](https://github.com/cosmos/interchain-accounts-demo)
Removed newline from end of error message.
> Add types and functionality needed to start supporting interchain accounts testing

- conformance/test.go
- test/poll_for_state.go
- test/poll_for_state_test.go
"Not found" was an okay first pass. But for debugging, it's not super useful. The error message (although verbose) now inclues the error, the target packet, and all the resources searched for the target packet.
* I think verbose error messages are ok (even preferred) for ibctest.
> fix: More descriptive polling errors

- README.md
- conformance/relayersetup.go
- conformance/test.go
- interchain.go
The test is not yet complete because ibc.Relayer does not yet have a
CreateChannel method -- this was likely an oversight as all other tests
so far simply use CreateLink to create clients, connections, and
channels in one shot.
But this is another example of the Interchain type greatly simplifying
setup for a conformance test.
> Add relayer setup conformance test

- conformance/relayersetup.go
- ibc/Relayer.go
- relayer/rly/cosmos_relayer.go
This was one missing piece in the relayer setup conformance test.
> Add CreateChannels method to ibc.Relayer

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
- ibc/types.go
- relayer/docker.go
- relayer/options.go
- relayer/rly/cosmos_relayer.go
- relayerfactory.go
Renames `ibc.ChainDockerImage` to `ibc.DockerImage` since it can also apply to the relayer.
Adds options to customize `DockerRelayer`:
- `RelayerOptionDockerImage` to use a custom docker image
- `RelayerOptionImagePull` to optionally disable image pull (helpful for local relayer images)
> DockerRelayer options

- chainset.go
- internal/blockdb/chain.go
- internal/blockdb/migrate.go
- internal/blockdb/migrate_test.go
- internal/blockdb/sql.go
- internal/blockdb/sql_test.go
- internal/blockdb/test_case.go
Solves the problem if someone sends us a db file, we'll be able to know which version of ibctest produced that file. 
* Git sha is also captured in `test_case` table but this is more explicit.
> feat: Keep track of git commit in sqlite in a schema_version table

- conformance/test.go
Hopefully resolves https://github.com/strangelove-ventures/ibctest/issues/112
I ran this 4-5 times locally and did not see the `height_timeout` test fail. Normally, I would've seen it fail at least one.
> fix: Wait for blocks before asserting balances for timeout tests

- .github/workflows/tests.yml
- chainset.go
Addresses:
https://github.com/strangelove-ventures/ibctest/runs/6757520076?check_suite_focus=true#step:4:1058
> Failed to chain gaia-9 to database: SQL logic error: table chain has no column named chain_id (1)Failed to chain osmosis-10 to database: SQL logic error: table chain has no column named chain_id (1)=== RUN   TestConformance/chain_pairs/gaia-9@v7.0.1+osmosis-10@v7.2.0/rly@v2.0.0-beta4/relayer_setup/generate_path
In the context of a self-hosted test-runner, I feel cleaning up the environment before each test run is wise. Otherwise, something like this database will expand uncontrollably.
> fix: Sqlite errors on CI

- chainset.go
- interchain_test.go
When importing the current version of ibctest into relayer, this error occurs if the BlockDatabaseFile field is provided but the GitSha is empty:
```
failed to track blocks: migrate sqlite database :memory:; deleting file recommended: upsert schema_version with git sha : constraint failed: CHECK constraint failed: length(git_sha) > 0 (275)
```
Default the git sha to `unknown` before attempting to add it to `schema_version` table, so that the GitSha is optional as documented.
> Add test ensuring git sha can be omitted from interchain build options

- internal/blockdb/migrate.go
- internal/blockdb/views_test.go
This view materializes the transactions, joined with blocks, chains, and
test cases.
This is a helpful view for users who are directly interacting with the
sqlite database.
I intend to follow this up with another view that relies on this view,
and parses relevant client/connection/channel details from the tx
objects using sqlite's json functions.
> Add tx_flattened view to blockdb

- chainset.go
- internal/blockdb/chain_test.go
- internal/blockdb/migrate.go
- internal/blockdb/migrate_test.go
- internal/blockdb/test_case.go
- internal/blockdb/test_case_test.go
- internal/blockdb/views_test.go
Given ibctest supports many types of chains, we need to be explicit about the chain type (ecosystem). Any debugging tools can leverage this extra dimension to present more advanced debugging options for cosmos like the messages view from https://github.com/strangelove-ventures/ibctest/pull/133.
Supports: https://github.com/strangelove-ventures/ibctest/issues/123
> feat: Capture chain_type in sqlite chain table

- test/wait_for_blocks.go
- test/wait_for_blocks_test.go
Resolves https://github.com/strangelove-ventures/ibctest/issues/130
The tradeoff to this fix is that if a chain always returns 0 height, `WaitForBlocks` could block indefinitely. However, we've already made the assumption a chain monotonically increases its height. If not, `WaitForBlocks` may block program execution.
We could take steps to mitigate, but my assumption is the above scenario is highly unlikely.
> fix: Intermittent panic when WaitForBlocks height is 0

- conformance/flush.go
- conformance/test.go
- ibc/relayer.go
- internal/blockdb/messages_view_test.go
- relayer/capability.go
- relayer/docker.go
- relayer/rly/cosmos_relayer.go
The previous ClearQueue method only flushed packets.
Both FlushPackets and FlushAcknowledgements are intended to be run as
one-off commands that do one chunk of work and stop. This is useful for
tests that need to make one unit of progress before making a set of
assertions.
In the future we may add a function like ClearQueue to the test package,
but for now the choices are StartRelayer, or manual flushing.
> Add FlushPackets and FlushAcknowledgements to ibc.Relayer

- internal/blockdb/messages_view_test.go
- internal/blockdb/migrate.go
As noted in a SQL comment, I'm still not certain if this source and
destination ports are the right direction; during test, both ends of the
path have the same channel and port, so it isn't simple to
programmatically tell the difference.
> Expand v_cosmos_messages test to MsgAcknowledgement

- Makefile
Easy to forget to run `go generate`. 
Code generation is run as part of creating the ibctest binary, `make ibctest`.
* May slightly slow down creating the binary.
* I've had CI steps that fail if code generation causes a dirty git state. But I don't think we need to go that far now.
> chore: Run code generation

- chain/cosmos/chain_node.go
- chain/penumbra/penumbra_app_node.go
- relayer/docker.go
I continue to see regular hangs in Docker. I've added context timeouts
in a few places where commands should complete quickly, and I've updated
the docker wrapper for the relayer to respect context cancellation in
more docker API calls.
Now, instead of waiting for go test's default 10m timeout when a
container gets stuck in the Created state, you may instead see a context
deadline exceeded error like this:
failed to restore key to relayer r for chain g0: context deadline exceeded
> Use timeouts for some docker operations

- relayer/rly/cosmos_relayer.go
And update capabilities to match. Now, the full test suite from ibctest
should not skip any relayer tests due to missing capabilities.
> Default to rly v2.0.0-rc1

- internal/blockdb/tui/help.go
- internal/blockdb/tui/presenter/highlight.go
- internal/blockdb/tui/presenter/highlight_test.go
- internal/blockdb/tui/update.go
- internal/blockdb/tui/update_test.go
- internal/blockdb/tui/views.go
Allows users to search text which gets highlighted in the associated text view. 
The last TUI feature I'll tackle before calling this MVP done is the ability to download the txs as a JSON array in case the user wants to use alternate tools to slice and dice the txs.
* The UX may be a little confusing. It searches across all txs, highlighting all words so you can flip between txs without having to redo the search on every page.
> feat: Add search feature to debug TUI

- chain/penumbra/penumbra_app_node.go
Update several docker library calls to respect the caller's context, and
fix a timeout argument that was supposed to be whole seconds as a uint.
> Fix context usage in penumbra node

- internal/blockdb/messages_view_test.go
These two spots had somewhat frequent failures due to the following
queries returning no rows, so wait for one block in order to give the
block collector more time to detect the new blocks, before attempting to
execute the queries.
> Add block waits in message view tests

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_chain.go
I am still seeing regular Docker hangs, but this increases the number of
call sites where a canceled context would be respected.
> Respect context in more node methods

- chainset.go
- conformance/flush.go
- conformance/relayersetup.go
- interchain.go
- interchain_test.go
- internal/blockdb/collect.go
- internal/blockdb/collect_test.go
- test_setup.go
This cleans up any created resources from Build(). The actual docker
containers are torn down via t.Cleanup, but the block collector
goroutine associated with the chainSet is now destroyed upon call to
Close, which reduces the number of goroutines present in a stack trace
due to a panic, test timeout, or deliberate SIGQUIT.
This PR is split into two commits for easier reading if so desired.
> Add (*Interchain).Close method

- conformance/test.go
A baby step towards https://github.com/strangelove-ventures/ibctest/issues/152
I originally wanted to rename this function from `TestChainPair` to `TestIBCTransfer`. However, I held off because I'm not sure how this function will evolve. It may be more efficient (like test setup) to keep adding scenarios to `TestChainPair`.
I like the pattern where the relayer has 2 separate conformance tests for setup and flush. 
I would love to constrain conformance tests to 2-chain-1-relayer, but that may not be possible for a scenario like packet-forward-middleware. 
In the above case where, for instance, 3 chains are needed, I advocate for a separate conformance test like `TestPacketForwardMiddleware` that requires 3 chains and 1 relayer. But it may cause issue when running ibctest conformance tests …
> docs: Add clarity for conformance tests

- .github/workflows/tests.yml
The "clean" step had this error:
line 1: -: command not found
because it was trying to pipe the output of "-" into rm.
Thanks to https://yaml-multiline.info/ for supplying a clear explanation
of the correct syntax.
> Fix YAML multiline syntax

- internal/blockdb/migrate.go
Some events do have an empty value, such as the connection_open_init
type, at least sometimes when the key is counterparty_connection_id.
Disallowing this caused the collector to be stuck in a loop on repeated
failures to save the attribute.
This should fix the consistent failure on the messages view test.
> Remove non-empty constraint from attr values

- ibc/relayer.go
- interchain_test.go
- relayer/docker.go
- relayer/rly/cosmos_relayer.go
This PR exposes relayer account information through the `Relayer` interface.
closes #159
> Expose relayer account information

- chainset.go
- interchain.go
- internal/blockdb/collect.go
I needed these logs to assist with #165, but I would not keep them on by
default -- hence opting in to the logs with the new Interchain WithLog
method.
> Allow collector logs to populate through Interchain

- internal/blockdb/messages_view_test.go
- internal/blockdb/migrate.go
- internal/blockdb/sql_test.go
This sets two pragmas on the database, which requires that callers do
run Migrate before accessing the database.
Now, it should be trivial to configure all tests to use the same
database file on disk and concurrently read and write without
encountering "database is locked" errors.
Closes #138.
> Support concurrent reads/writes against blockdb

- README.md
- chain/penumbra/penumbra_chain_test.go
- conformance/flush.go
- conformance/relayersetup.go
- conformance/test.go
- interchain_test.go
- internal/blockdb/messages_view_test.go
- tempdir.go
- tempdir_test.go
This behaves similarly to `(*testing.T).TempDir()`, except that it
supports runtime configuration to determine whether to remove created
directories for failed tests.
By default, the created directories are removed as part of t.Cleanup. If
the environment variable `IBCTEST_KEEP_FAILURE_DIR` is set to any
non-empty value, and if the test failed, then the test will log that the
directory is not being cleaned up.
Importers of the ibctest package also have the option to set the package
level variable `KeepTempDirOnFailure` to opt in to this behavior.
Closes #168.
> Add ibctest.TempDir function

- chain/cosmos/chain_node.go
This step fails somewhat frequently on my workstation, with 100 tries of
a message like this:
post failed: Post "http://localhost:55493": dial tcp [::1]:55493: connect: connection refused
I'm not sure why it is refusing the connection, but 100 tries with a 5s
sleep between each try is over 8 minutes of waiting to find out that the
test will fail.
Arbitrarily reduce the tries to 40 and the inter-try sleep to 3s, so
that this will only try for about 3 minutes.
> Reduce timeout on starting container for cosmos chain node

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/penumbra/penumbra_chain.go
- ibc/chain.go
- ibc/types.go
- interchain_test.go
- test_user.go
This PR adds the functionality to recover a test user from a given mnemonic.
Tests have been added which verify that users can be created using `CreateKey` and `RecoverKey`
closes #169
> Adding support for `RecoverKey` in the chain interface.

- conformance/flush.go
- conformance/relayersetup.go
- ibc/relayer.go
- ibc/relayer_test.go
- interchain.go
- internal/blockdb/messages_view_test.go
- relayer/docker.go
- relayer/rly/cosmos_relayer.go
- test_setup.go
This PR addresses #155 by adding adding `CreateChannelOptions` as a field to the `InterchainBuildOptions` struct as well as adding it as a parameter to `LinkPath`.
If `CreateChannelOptions` are not specified on the `InterchainBuildOptions` struct then when the paths are linked in `interchain.Build` we default to the channel configuration options for an ics20 token transfer channel.
> Add support for declaring the channel configuration options

- relayer/docker.go
- relayer/options.go
- relayer/rly/cosmos_relayer.go
- relayerfactory.go
`StartupFlags` `RelayerOption` to append to the `StartRelayer` `commander` command. Will need to be implemented if needed separately for future `RelayerCommander` implementations.
> RelayerOption for additional startup flags

- chain/cosmos/chain_node.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- ibc/types.go
- internal/dockerutil/image.go
- relayer/docker.go
So that we can consistently generate the image reference, i.e.
`$REPO:$TAG`. If we later support image hashes, this method will generate
the proper `$REPO@sha256:$HASH` format.
Followup from #187.
> Add Ref() method on ibc.DockerImage

- internal/dockerutil/setup.go
Cleaning up containers was mistakenly using a syntax that would not
match anything, causing containers to be left behind on test runs, and
breaking following tests.
> Fix label filter on Docker cleanup

- examples/packet_forward_test.go
This PR adds a standalone test, for the IBC [packet-forward-middleware](https://github.com/strangelove-ventures/packet-forward-middleware), to an `examples` directory.
The test asserts that token transfers work in both directions using the middleware and also has the funds returned to the appropriate address in the case of one hop failing.
> Add example test for packet forward middleware

- chain/penumbra/penumbra_app_node.go
- internal/dockerutil/image.go
The entrypoint was unspecified in two ContainerCreate calls, resulting
in the possibility of being unable to construct custom commands.
Closes #183.
> Use empty entrypoint in every ContainerCreate call

- chain/cosmos/chain_node.go
- internal/blockdb/chain.go
- internal/blockdb/tui/presenter/tx.go
- internal/blockdb/tui/update_test.go
- tempdir.go
- tempdir_test.go
- test/poll_for_state.go
- testreporter/reporter.go
- testreporter/reporter_test.go
```
gofmt -w -r 'interface{} -> any' .
```
This may make use of build tags tricky if we ever need to go that route to support ibc-go multiple versions. 
But the inverse is easy:
```
gofmt -w -r 'any -> interface{}' .
```
> refactor: Interface{} to any

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- internal/dockerutil/fileretriever.go
- internal/dockerutil/fileretriever_test.go
This is one step towards #200, using ephemeral containers to read the
genesis file content from the docker volume instead of reading from the
host disk.
Note that as of this commit, the docker volume is still a host mount,
but it should be seamless to switch this usage to a volume once
everything else for #200 is in place.
> Use docker to retrieve genesis hashes

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- internal/dockerutil/filewriter.go
- internal/dockerutil/filewriter_test.go
This is another step in avoiding modifying files on the host, in support
of #200.
> Use Docker API to copy genesis files to all nodes

- internal/dockerutil/busybox.go
- internal/dockerutil/fileretriever.go
- internal/dockerutil/filewriter.go
- internal/dockerutil/volumeowner.go
- relayer/docker.go
This behavior already existed internally in the relayer docker
boilerplate; extract it to a standalone function in the dockerutil
package so that it can be used more generally, in an upcoming change to
use volumes for cosmos chain containers.
Also move the busybox helpers to their own file.
> Extract SetVolumeOwner function in dockerutil

- internal/mocktesting/doc.go
- internal/mocktesting/t.go
- internal/mocktesting/t_test.go
- tempdir_test.go
- testreporter/reporter_test.go
To add tests around an upcoming feature (opt-in retention of Docker
volumes on test failure), I was going to need a third instance of a mock
*testing.T.
This extracts a more full-featured mock instance of *testing.T to be
used in existing and future tests that need to assert against
interactions with real tests.
> Extract mocktesting package

- README.md
- internal/dockerutil/setup.go
- internal/dockerutil/setup_test.go
- tempdir.go
- tempdir_test.go
- test_setup.go
(Draft until #212 is merged.)
Only if that environment variable is non-empty and the test fails.
As of this commit, this only skips calling docker volume prune on the
volumes. The next step in this sequence will be to add an option to copy
the volumes' content to local disk.
> Use IBCTEST_SKIP_FAILURE_CLEANUP to retain Docker volumes

- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
Still using the host mounts rather than independent Docker volumes at
this point, but changing internal file copying to use the
volume-compatible APIs for a simpler switchover later.
For #200.
> Begin changing chain/internal/tendermint to use Docker volumes

- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
I think this is all the outstanding os.WriteFile and os.ReadFile calls.
This should enable switching the host mounts to docker volumes in an
upcoming commit.
For #200.
> Migrate remaining direct file writes to docker operations

- chain/cosmos/broadcaster.go
- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
- internal/dockerutil/image.go
- internal/dockerutil/setup.go
- relayer/docker.go
Complete the migration from host mounts to Docker volumes.
I wanted to split this into smaller steps, but it seemed that this last step needed to happen all at once.
Switch all the chains to using Docker volumes, default to the containers' default Docker user in most circumstances, and add an additional label to volumes to make post hoc debugging a little simpler.
Closes #200.
> Migrate to Docker volumes

- internal/dockerutil/volumeowner.go
This allows the icad image, which is based on ubuntu, to correctly set
the volume owner. Otherwise the chown command fails because we try to
set ownership to a nameless user.
> Default to root user when setting volume owner

- ibc/relayer.go
- relayer/docker.go
This PR adds a `HomeDir` function to the `relayer` interface. Being able to execute arbitrary commands from the `relayer` means that we will need to pass the `--home` flag to commands and this is currently unavailable via the current interface.
> Expose `HomeDir` function on relayer interface

- chain/cosmos/cosmos_chain.go
- chain/penumbra/penumbra_chain.go
- chain/penumbra/penumbra_chain_test.go
- chainset.go
- conformance/flush.go
- conformance/relayersetup.go
- conformance/test.go
- examples/packet_forward_test.go
- ibc/chain.go
- interchain.go
- interchain_test.go
- internal/blockdb/messages_view_test.go
- test_setup.go
Now that we are using Docker volumes everywhere, the home directory is
unused and is no longer necessary for the Chain.Initialize method.
Also plumb context through to address a couple context.TODO calls.
> Remove home directory from chain initialization

- ibc/relayer.go
- relayer/docker.go
This makes it possible for third parties to provide Relayer
implementations.
And remove the HomeDir method from the Relayer interface, as that is an
implementation detail of the DockerRelayer type.
> Use exported return type in Relayer.Exec

- chain/polkadot/polkadot_chain_test.go
- chainfactory.go
- chainspec.go
Wires up `polkadot` chain in `ChainFactory`, only handling `composable` as a supported parachain for now.
Adds config overrides in `ChainSpec` for `polkadot` to configure the docker image versions.
Adds test for polkadot chain to ensure relay chain and parachain can start and that composable chain produces 10 blocks.
> Polkadot ChainFactory, ChainSpec, and test

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chainspec.go
- examples/state_sync_test.go
- examples/upgrade_test.go
- go.mod
- go.sum
- ibc/types.go
- internal/configutil/toml.go
- test/wait_for_blocks.go
- test/wait_for_blocks_test.go
Adds a cosmos chain state sync test to the examples:
- Start chain using a short state-sync snapshot interval of 10 blocks
- Wait for chain to produce twice as many blocks
- Fetch latest height from chain, then subtract snapshot interval for trusted height
- Fetch block ID hash for the trusted height
- Add new full node with statesync params `trust_hash` and `trusted_height` for the proof of trusted height, and `rpc_servers` for verification, which is just the first full node twice.
- Wait for new full node to complete state sync and get in sync with the chain
Cleanup:
- Instead of overwriting the tendermint config.toml when setting peers, we can use the config.toml that was generated during the config init step. The config changes can be applied overtop using …
> Add cosmos state sync test

- chain/cosmos/cosmos_chain.go
- chain/penumbra/penumbra_chain.go
- chain/polkadot/polkadot_chain.go
- cmd/ibctest/example_matrix_custom.json
- examples/interchain_queries_test.go
- ibc/types.go
- internal/dockerutil/volumeowner.go
- relayer/docker.go
- relayer/options.go
- relayer/rly/cosmos_relayer.go
Problem: new slim heighliner images don't have `chown` or `chmod`.
Adds `UidGid` parameter to `ibc.DockerImage`. If empty, root user is assumed. If non-empty, `uid:gid` format is required so that busybox can change ownership without knowing the contents of the target image's `/etc/passwd`
With this, we don't need to assume that any other custom images would have `chown` or `chmod` either.
> Fix volume ownership when heighliner images don't have chown or chmod

- chainspec.go
- ibc/types.go
Allows chain config to be constructed for non built in chains as long as they are fully configured.
Passes along gas adjustment value if non-zero
> Fix fully configured custom chains

- conformance/flush.go
- examples/interchain_queries_test.go
- interchain.go
- test_setup.go
Move `CreateClientOptions` and `CreateChannelOptions` to `InterchainLink` to allow differences for different paths.
> InterchainLink create client/channel opts

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- cmd/ibctest/ibctest_test.go
- conformance/flush.go
- conformance/relayersetup.go
- conformance/test.go
- examples/cosmos_chain_upgrade_ibc_test.go
- examples/cosmos_chain_upgrade_test.go
- examples/interchain_queries_test.go
- examples/packet_forward_test.go
- examples/state_sync_test.go
- ibc/types.go
- test_setup.go
Tests IBC conformance on both sides of an upgrade.
Includes changes to conformance suite to:
- Allow calling `conformance.TestChainPair` from example tests. `CosmosChainUpgradeIBCTest` uses this to test before and after the upgrade
- Fund different random users for each `conformance.TestChainPair` run so that wallets are isolated
- Test multiple paths simultaneously
> Upgrade IBC test

- chainspec.go
This PR fixes an issue when passing in custom matrix files.
If the chain is fully configured but not pre-configured, we need to register a new chain label. 
Closes: https://github.com/strangelove-ventures/ibctest/issues/263
> Fix issue with custom matrix files

- internal/dockerutil/volumeowner.go
This fixes a panic we were seeing on some tests when the user did not have the busybox image.
> Ensure Busybox image exists before creating Busybox container 

- chain/cosmos/chain_node.go
Tracks begin and end block events in blocks db.
Ensures txs are saved with `Data` in json format so that `v_cosmos_messages` will be able to query even if transactions are unsuccessfully decoded
> blockdb - begin and end block events

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
DRY up the chain node flag usage within the cosmos `ChainNode`, exporting public helpers to get or execute the commands from test cases.
`BinCommand` - returns aggregate command of `command []string` args/flags after the chain node binary, with `--home` flag appended at the end.
`ExecBin` - executes aggregate command from `BinCommand`.
`NodeCommand` - returns aggregate command of `BinCommand` with additional flags `--node` and `--chain-id` appended, necessary when commands interact with the node URL.
`QueryCommand` - returns aggregate command of `NodeCommand` with prepended arg `query` and appended flag `--output json` to return response formatted as json.
`ExecQuery` - executes aggregate command from `QueryCommand`.
`ExecTx` - assembles aggregate command of `NodeCommand` with prepended …
> consolidate cosmos chain node commands

- chain/cosmos/broadcaster.go
- chain/cosmos/chain_node.go
- chain/cosmos/codec.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/query.go
- ibc/types.go
Allow overriding the default `EncodingConfig` for custom codecs.
Make `cosmos.DefaultEncoding()` public so that default config can be fetched, enriched, then used as an override.
Example usage:
https://github.com/strangelove-ventures/ibctest/blob/3669846acdc03d09f1b9756823952e199fe13667/examples/osmosis/osmosis.go#L10-L17
https://github.com/strangelove-ventures/ibctest/blob/3669846acdc03d09f1b9756823952e199fe13667/examples/osmosis/cosmos_chain_gamm_pool_test.go#L34
> EncodingConfig override

- .github/workflows/prior-version-pr.yml
In conjunction with #283 and #284, this will cherry pick merges to `main` into a branch and open a PR against `v3`.
If changes are not applicable to v3, the PR can be closed.
If there are merge conflicts, they can be handled in the PR
> Create PRs into v3 on merge to main

- chain/penumbra/penumbra_chain.go
- chain/polkadot/polkadot_chain.go
- ibc/chain.go
These methods are only applicable to cosmos chains for now, so they can be removed from the `ibc.Chain` interface. Tests that want to use these methods can cast the chain to a `*CosmosChain`.
> Remove cosmos specific methods from chain interface

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/osmosis.go
- chain/cosmos/poll.go
- chain/cosmos/types.go
- examples/cosmos_chain_upgrade_ibc_test.go
- examples/cosmos_chain_upgrade_test.go
- ibc/tx.go
- ibc/types.go
- test/poll_for_state.go
Add methods to `CosmosChain`:
- `QueryProposal` to fetch proposal information e.g. title, description, status, etc.
- `TextProposal` to submit a text governance proposal
Adds `cosmos.PollForProposalStatus` to poll for a proposal to change status, e.g. wait for proposal to transition from voting period to pass/fail status.
`CreatePool` was never fully implemented. This is used in #282 
Osmosis specific methods in their own file
> [v3] Proposal Polling and Pools

- .github/workflows/tests.yml
- chain/cosmos/cosmos_chain.go
- chainspec.go
- ibc/types.go
Fixes potential race condition due to concurrent `cf.Chains` calls here:
https://github.com/strangelove-ventures/ibctest/blob/main/conformance/test.go#L245-L270
Potentially source of startup hang reported by macOS users?
Also fixes a potential race with the block collector trying to collect blocks while the chain is starting back up after the upgrade
Adds race detection to CI
> fix race conditions

- .github/workflows/tests.yml
- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chainspec.go
- cmd/ibctest/ibctest_test.go
- examples/cosmos_chain_upgrade_ibc_test.go
- examples/interchain_queries_test.go
- examples/packet_forward_test.go
- ibc/relayer.go
- ibc/types.go
- interchain.go
- interchain_test.go
- relayer/docker.go
- relayer/rly/cosmos_relayer.go
- test_user.go
- Link paths in parallel to speed up tests now possible with https://github.com/cosmos/relayer/pull/987. Tests will pass once we update the go relayer `DefaultContainerVersion` to a release version that has this included.
- Faucet reqs in parallel to speed up tests
- Multiple paths same process
- Use native denom instead of `stake` for delegation. Increase faucet amount. 
- Pass bech flag to KeyBech32.
> Updates for rly v2.1.0

- chain/penumbra/penumbra_chain.go
- chain/polkadot/polkadot_chain.go
- chainfactory.go
- chainspec.go
- chainspec_test.go
- cmd/ibctest/matrix_test.go
- configuredChains.yaml
- docs/conformanceTests.md
- docs/preconfiguredChains.txt
- docs/writeCustomTests.md
- ibc/types.go
This PR moves the builtin chains from a hardcoded struct to a yaml file.
This makes it straight forward for testers to view and edit the "preconfigured" settings.
Ibctest will embed ./confiugredChains.yaml. It will refer to this embedded version UNLESS the environment variable  IBCTEST_CONFIGURED_CHAINS is set to a path for "custom" preconfigured chains and settings.
This should satisfy: https://github.com/strangelove-ventures/ibctest/issues/175
> move builtin chains to yaml file

- interchain.go
We identified a few places that would be helpful for building a noble chain example test:
- Allow providing additional genesis wallets through `Interchain`
- Make `BuildWallet` public so that it can be used in tests.
> Genesis wallets through Interchain

- chain/cosmos/poll.go
- examples/cosmos/light_client_test.go
- examples/cosmos/state_sync_test.go
- examples/cosmos/versions_test.go
- examples/ibc/learn_ibc_test.go
- test/poll_for_state.go
Adds a new poll function for cosmos chains. The ability to poll for any arbitrary cosmos message. 
I will use this in the relayer codebase to help with a test regarding keeping light clients up to date.
> feat: Add cosmos message poller

- chain/cosmos/chain_node.go
- chainspec.go
- ibc/relayer.go
- ibc/types.go
- interchain.go
- relayer/docker.go
- relayer/rly/cosmos_relayer.go
The PR adds the ability to specify Coin Types when creating or restoring keys for chains. 
The coinType is invoked in the chainConfig but defaults to "118" (Cosmos SDK default) if the key:value pair is left blank.
> Integrate coin-type configuration

- relayer/docker.go
- Remove dependency on `chown` in rly image. Use existing dockerutil `NewFileWriter` instead. 
- Use relayer user home dir
> Changes for slim rly images

- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
- examples/penumbra/penumbra_chain_test.go
Since penumbra doesn't have "key names", we'll have the folder that houses the key act as the key name.
> Update penumbra key management

- examples/cosmos/chain_upgrade_ibc_test.go
- examples/cosmos/chain_upgrade_test.go
- examples/cosmos/state_sync_test.go
- examples/ibc/learn_ibc_test.go
- examples/ibc/packet_forward_test.go
- examples/ibc/wasm/wasm_ibc_test.go
- examples/ibc/wasm/wasm_icq_test.go
- examples/osmosis/cosmos_chain_expedited_proposal_test.go
- examples/osmosis/cosmos_chain_gamm_pool_test.go
- relayer/docker.go
When running multiple tests in parallel you hit a container name collision error if you are running a relayer on paths with the same names across those tests. This PR adds a random 5 character suffix to the relayer container names to avoid this ever happening.
Closes #375
> fix: add randomized suffix to relayer container names to avoid naming collisions

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chainspec.go
- ibc/types.go
- interchain.go
Adds `PreGenesis` hook to execute a function prior to genesis file creation. Adds `SkipGenTx` to skip validator gentx flow.
This is utilized currently in our consumer chain tests.
> PreGenesis hooks

- chain/cosmos/broadcaster.go
- chain/cosmos/wallet.go
Previously, when a transaction that was broadcast failed, we ended up discarding the result by returning an empty struct. This fix makes it so that when a tx fails, the result is correctly returned with all of the error messages intact.
This PR also ensures that the CosmosUser implements the User interface.
> Fix usage of broadcast mode sync in broadcaster.go

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
Some things old, some things new...
In writing some tests involving the impact of some module params on IBC transfers, we added a few new methods to the `CosmosChain`.
Submits a parameter change proposal to the gov module. For simplicity's sake (and since a majority of the `ChainNode` methods leverage the cosmos-sdk command-line interface to interact with the chain anyway) we borrowed our argument type directly from the `params` module's client utils module. Fairly straightforward and exposed at the `CosmosChain` level as well.
Uses the gRPC client (as `GetBalance` does) to query for all of the coins held by an account address. Almost a carbon-copy of `GetBalance`.
After encountering some unexpected behaviors in our tests, we found what we believe to be a bug in the `SendIBCTransfer` …
> Param proposals, balance inquiries, and IBC transfer error handling

- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
- examples/penumbra/penumbra_chain_test.go
This PR makes the `TestPenumbraChainStart` test pass again.
The latest Penumbra binary starts to move some exports from `json` to `toml`.
It should be noted that the key name `funding_streams` is plural in `json` but singular (`funding_stream`) in toml.
> Bring up to date with latest Penumbra binary

- ibc/relayer.go
- relayer/rly/cosmos_relayer.go
This PR aims to provide an addtion of : 
- Override flag in CreatChannelOptions to have a capability of passing `--override` flag in CreateChannel transaction.
> Adding override flag in CreatChannelOptions.

- chain/cosmos/chain_node.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_app_node.go
- chain/polkadot/parachain_node.go
- chain/polkadot/relay_chain_node.go
- internal/dockerutil/ports.go
Generate explicit port bindings to workaround [docker bug](https://github.com/moby/moby/issues/42442). This retains automatic port allocation functionality by opening temporary listeners on the next available port and holding that listener open until the handoff to docker for the container to consume the port.
Resolves #443
> generate explicit port bindings

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/types.go
- examples/cosmos/chain_param_change_test.go
- examples/cosmos/params/IncreaseValidatorsParam.json
- examples/cosmos/versions_test.go
Closes #464 . Targeting v4 branch here
- Once approved, should I make another PR targeting main?
- Adds a way to query a subspace param
- ParamChangeProposal
- Example test in action
- We need this in v4 for Juno to test lowering unbonding period & the effects on IBC & GlobalFee
- Noble (v3) also has globalfees, so this is helpful to test that too with e2e per the todo https://github.com/strangelove-ventures/noble/pull/146
> Adds ParamChangeProposal

- relayer/hermes/hermes_commander.go
- relayer/hermes/hermes_relayer.go
Basically three changes:
- Fix the endpoints when querying a channel, they were in reverse order.
- Pass the `channel-version`, if applicable, and `order` during channel creation.
- Pass the trusting period, if applicable, to the client during creation.
Found while trying to integrate hermes in our e2e tests https://github.com/cosmos/ibc-go/pull/3408
> Fix issues with hermes client, channel creation and channel queries.

- examples/cosmos/sdk_47_boundary_test.go
- relayer/rly/cosmos_relayer.go
Bump rly default version to v2.3.1 and remove custom image for tm v0.37 boundary test
> Bump rly default version to v2.3.1

- relayer/hermes/hermes_relayer.go
Changes the registry to ghcr which hermes is now using and bumps the version.
> Use ghcr registry for hermes, bump version.

- relayer/hermes/hermes_commander.go
- relayer/hermes/hermes_relayer.go
Similarly to `rly`, allows some startup flags to be provided per instantiation instead of hardcoding them in the `StartRelayer` function.
Ideally, none of the tests in interchaintest should be tweaked.
> Allow extra startup flags for hermes.

- chain/cosmos/chain_node.go
> fix: moved '--chain-id' flag from NodeCommand to TxCommand

- .github/dependabot.yml
- .github/mergify.yml
- README.md
This PR:
- Updates the `Maintained Branches` Table on the Readme
- Updates the Mergify rule 
- Will not backport PR's to `v3` OR `v3-ics` anymore
-  Instead of backporting all PR's EXCEPT if they have a `dont_backport` lable, this changes the rule to only backport PR's that have a `BACKPORT` label.
- I think this makes more sense as there will most likely be more PR's pointed at specific branches.
- It also updates the rule to not only backport PR's merged into `main`, but now allows for PR's to be targeted to any of our maintained branches to also be backported. EXAMPLE: PR targeted at `v5` branch with the backport label will also get "backported" into `main`.
- Because of this rule change, dependabot does not need to label with `dont_backport` anymore
(Branch protection rules already …
> Update Readme + Mergify Rule for Maintained Branches

- .github/mergify.yml
We don't want Mergify to add the `BACKPORT` label to a PR it already backproted. 😵‍💫 
This will cause to try and backport it again.
Instead lets add a `backported` label.
> fix: mergify labeling

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/poll.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_chain.go
- chain/polkadot/parachain_node.go
- chain/polkadot/polkadot_chain.go
- chain/polkadot/query.go
- chain/polkadot/relay_chain_node.go
- chain/polkadot/tx.go
- conformance/flush.go
- conformance/test.go
- examples/cosmos/light_client_test.go
- examples/hyperspace/hyperspace_test.go
- examples/ibc/interchain_accounts_test.go
- examples/ibc/learn_ibc_test.go
- examples/ibc/packet_forward_test.go
- examples/ibc/wasm/wasm_ibc_test.go
- examples/ibc/wasm/wasm_icq_test.go
- examples/polkadot/polkadot_chain_test.go
- examples/polkadot/push_wasm_client_code_test.go
- go.mod
- ibc/chain.go
- ibc/types.go
- interchain.go
- interchain_test.go
- internal/blockdb/messages_view_test.go
- test_user.go
Previously we were using `int64` to represent token amounts for things like transfers and balance checks. This becomes problematic when dealing with the EVM or chains like Penumbra where we may need to handle `int128` or `int256`. 
Since Go does not have native support for integer values larger than 64-bits we would need to use the stdlib's [big package](https://pkg.go.dev/math/big#Int). The Cosmos SDK's math package contains its own [Int](https://github.com/cosmos/cosmos-sdk/blob/8aaa776f822392bd506feb16cf454709059265fa/math/int.go#L75-L80) type that is a wrapper around Go's `big.Int` and offers useful helper methods and enforces a 257 bit range by checking overflow, underflow and division by zero.
> refactor: use cosmos sdk Int type for balances/token amounts

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chainspec.go
- ibc/types.go
- I add functionality for retrieving the ContainerID of tendermint nodes in a cosmos-chain
- This is useful for copying data / directories from specific nodes
- I add functionality for Modifying the genesis delegation size / amounts for cosmos chains
- This is necessary for chains that support tokens scaled by 1e18 (evm-chains)
> feat(cosmos): Additional Helpers

- .github/mergify.yml
- README.md
Note from team:
Strangelove is sunsetting active maintenance for older versions of interchaintest (`v4`, `v4-ics` and `v5`). We will be focusing on releasing v8 with SDK 0.50.0 compatibility. 
We plan to actively maintain `n - 1` versions of ibc-go. Currently, that is `v6` and `v7`
---
These older branches will still exists! Backporting every new feature to all 4 branches has become a burden. 
Please reach out with any concerns! 
We are happy to backport on a case by case basis.
> Update maintained branches + readme

- chain/cosmos/chain_node.go
- examples/cosmos/chain_export_test.go
Closes #721 
If a chain is on SDK v47+, we should output exports to a file directly. Then we return the contents from this file instead of returning a messy stdout + err for parsing.
Tests both 45 and 47 usecases
> Cleaner ExportState via document for SDK v47+

- internal/dockerutil/ports.go
- internal/dockerutil/strings.go
- internal/dockerutil/strings_test.go
- local-interchain/README.md
- local-interchain/configs/server.json
- local-interchain/docs/REST_API.md
- local-interchain/docs/WINDOWS.md
- local-interchain/scripts/example_req.bash
- local-interchain/scripts/helpers/cosmwasm.py
closes #402
This PR moves any tcp references to localhost, and instead uses the direct IP, 127.0.0.1, in its place.
reasons:
- the /etc/hosts lookup itself is more sys calls when it is not required for an ipv4 enviroment
- localhost can reference multiple IP families (ipv6 & ipv4) on lookup. - This could cause unintended issues (overhead: query ipv6, fail, then try ipv4. Machines not routing and only doing v6)
> chore: move localhost -> 127.0.0.1

- chain/cosmos/cosmos_chain.go
Closes #401
Adds `GetNode()` which just returns validator in index 0.
- it is easy to try and grab full_node[0], even if you did not set any (per issue, as well as personally myself) when only a validator is set for speed.
- _'what about getFullNode()? just make that public'_ - if you run any test which add a full node later, it would break previous logic on the val you were operating on (I have had this happen). Thus having a function which ensures to get a valid node, and the same every time is the way to go imo
> add GetNode() helper

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
closes #809 
When writing CW test, I had to write helper methods to execute with other fees, amounts, and gas limits. This removes that for StoreCode's and contract Executes
> add extraExecTxArgs to other CosmWasm methods

- relayer/rly/cosmos_relayer.go
Previously the relayer startup flags were not being used in any of the commands because we were passing the `commander` by value to the `DockerRelayer` constructor and then attempting to mutate the local copy of `commander`
> fix: ensure that relayer startup flags are consumed properly

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/types.go
- examples/cosmos/chain_miscellaneous_test.go
- Added helper functions to query a module account information.
- With x/gov v1 types, the governance module address is likely to be used quite often. `chain.GetGovernanceAddress()` would be nice to have
> feat: adding query to fetch x/gov module address

- chain/cosmos/broadcaster.go
When working on the 08-wasm tests, the `MsgStoreCode` message was quite large, and was not included in a block by the time the `authtx` function was being called. 
This PR adds polling to periodically attempt to fetch the tx. It will fail if the tx is still not found after the interval.
> Support larger tx sizes from cosmos Broadcaster

- examples/ibc/client_creation_test.go
- ibc/relayer.go
- relayer/docker.go
- relayer/hermes/hermes_commander.go
- relayer/hermes/hermes_relayer.go
- relayer/hyperspace/hyperspace_commander.go
- relayer/rly/cosmos_relayer.go
Prior to this PR, `createClient` was not wired up.
> Fixes and wires up `CreateClient`

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/module_gov.go
- chain/cosmos/poll.go
- chain/cosmos/query.go
- chain/cosmos/types.go
- chain/ethereum/ethererum_chain.go
- chain/ethereum/unimplemented.go
- chain/internal/tendermint/tendermint_node.go
- chain/penumbra/penumbra_chain.go
- chain/polkadot/polkadot_chain.go
- chainset.go
- conformance/test.go
- examples/cosmos/chain_miscellaneous_test.go
- examples/cosmos/chain_upgrade_ibc_test.go
- examples/hyperspace/hyperspace_test.go
- examples/polkadot/push_wasm_client_code_test.go
- ibc/chain.go
- ibc/tx.go
- ibc/types.go
- internal/blockdb/chain.go
- internal/blockdb/collect.go
- internal/blockdb/collect_test.go
- internal/blockdb/query_test.go
- testutil/poll_for_state.go
- testutil/poll_for_state_test.go
- testutil/wait.go
- testutil/wait_test.go
CometBFT [(here)](https://github.com/cometbft/cometbft/blob/c920404f6b56fc9c366aee8774c4d011610c564d/proto/cometbft/state/v1/types.proto#L77) and Cosmos-sdk [(here)](https://github.com/cosmos/cosmos-sdk/blob/74dfab268484d3606e9df8cbc66327a6c627f29d/proto/cosmos/base/tendermint/v1beta1/types.proto#L27) both use `int64` to denote block height.
Currently the interchaintest framework uses `uint64` for all height related values.
This PR changes that to use `int64` instead. This would help in preventing frequent typecasting and ensure consistency with upstream types.
> refactor!: changing block height type from uint64 to int64

- chain/cosmos/cosmos_chain.go
Sequence numbers are defined as uint64 in the spec:
https://github.com/cosmos/ibc/blob/ded4eb44d8c6b4d32d386728414bec3999fa069a/spec/core/ics-004-channel-and-packet-semantics/README.md?plain=1#L119-L128
Closes #977
> fix: Parse sequence number as uint instead of int in cosmos SendIBCTransfer

- local-interchain/README.md
while going through the local interchain setup i noticed that the paths suggested in the `Running` section seem to be off.
same jsons were present under `/chains`, hence this small pr.
> fix: local interchain readme

- local-interchain/chains/base_ibc.json
- local-interchain/chains/cosmoshub.json
- local-interchain/chains/juno_ibc.json
- local-interchain/chains/stargaze.json
- local-interchain/cmd/local-ic/interaction.go
- local-interchain/cmd/local-ic/main.go
bash / CURL interaction is a pain, CLI it - requirement for spawn
```
curl -X POST -H "Content-Type: application/json" -d '{
"chain_id": "localcosmos-1",
"action": "query",
"cmd": "bank balances cosmos1hj5fveer5cjtn4wd6wstzugjfdxzl0xpxvjjvr"
}' http://127.0.0.1:8080/
```
```
local-ic interact localcosmos-1 query bank balances cosmos1hj5fveer5cjtn4wd6wstzugjfdxzl0xpxvjjvr
```
> feat: local-ic native cli interaction

- chain/cosmos/account_retriever.go
- chain/cosmos/address.go
- chain/cosmos/broadcaster.go
Closes #1008
This PR adds a custom implementation of the `AccountRetriever` (copied from auth module) which is modified to convert an `AccAddress` to string using the target chain's bech32 prefix.
> feat: replace broadcaster's account retriever to use chain's bech32 prefix when converting AccAddress to string

- chain/cosmos/account_retriever.go
- chain/cosmos/broadcaster.go
Resolves the conflicts of #1010
> fix: resolve conflicts of [BP: v7 <- #1009]

- examples/ibc/ics_test.go
- relayer/hermes/hermes_commander.go
- relayer/hermes/hermes_relayer.go
Allows the Hermes relayer to be used with ProviderConsumerChainLinks by implementing UpdatePath; adds a test to the example `ics_test.go`.
I'm not sure how we'd implement the channel filter, but this at least allows for basic ICS tests to be written against hermes.
> feat[v7]: allow hermes to work with ics

- local-interchain/chains/interchainsecurity.json
- local-interchain/interchain/start.go
- local-interchain/interchain/types/chain.go
request by timewave
Adds ICS support to local-interchain in a user friendly way with only 1 configuration change needed. Supports multiple consumers -> 1 provider
Add `"ics_consumer_link": "providerchainid-1",` to your consumer chain. No changes on the provider side is required
`make install && local-ic start interchainsecurity`
> feat[v7]: support interchain security in local-interchain

- chain/cosmos/cosmos_chain.go
- examples/cosmos/chain_genesis_stake_test.go
- ibc/types.go
Closes #1027 
Some issues only arise when there's an unequal distribution of stake among validators. This PR allows interchaintest to create chains whose validators have different stake. It does this by changing the `ModifyGenesisAmounts` function in the chain config so that it takes in an index; the returned values will be used as the genesis and self-delegation amounts for the validator at that specific index.
> feat(v7)!: validators can have different genesis and self-delegation amounts

- relayer/hermes/hermes_config.go
- relayer/hermes/hermes_relayer.go
Closes https://github.com/strangelove-ventures/interchaintest/issues/1063
I used this patch locally and got past the error mentioned in the issue but I'm not 100% sure everything is resolved yet b/c my test is failing on something else
> feat!: update hermes config

- chain/cosmos/cosmos_chain.go
Reference https://github.com/cosmos/ibc-go/pull/6023
It seems like there's no other spot events are currently parsed? Either way, can leave as draft and trigger a run of our e2es to see the green ticks before opening.
> chore!: Parse packet data from the packet_data_hex attribute

- chain/cosmos/chain_node.go
- ibc/types.go
by exposing the ports defined in HostPortOverride on only the first _validator_ node of the chain, it can now be run with full nodes alongside without port binding conflicts.
For full description of issue, see #1089
> fix: allow use of HostPortOverride with full nodes

- chain/cosmos/chain_node.go
- examples/cosmos/chain_miscellaneous_test.go
Sometimes a transaction returns code 0 initially, but then fails when a validator goes to actually include it in a block. This PR adds code to cosmos' ExecTx to make sure transactions are verified after their inclusion in a block; if they fail at any stage of proceedings, an error is returned.
> fix(v7)!: check transactions succeed after they're included in a block

- chain/cosmos/chain_node.go
- chainspec.go
- examples/cosmos/ethermint_test.go
- ibc/types.go
for cosmos chains, `ExposeAdditionalPorts` takes a list of port ids that will be exposed on all validators and full nodes for the chains on random host ports.
extends the ethermint test by exposing the EVM & verifying the port actually gets exposed.
Resolves cosmos chain portion of #1091 
Happy to make any changes or refactors. I _think_ I updated all the config things that need updated (`Clone` & `MergeChainSpecConfig`), but possible I missed something.
> feat: add ExposeAdditionalPorts config option

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- examples/ibc/ics_test.go
- go.mod
Instead of building the ccv genesis for the consumer, we can fetch it from the provider chain. This is preferred, as it guarantees that it works across different consumer/provider versions of ICS
> refactor(v7): get consumer genesis from provider chain and transform it

- ibc/types.go
GasAdjustments configured via the ChainConfig were being ignored.
> fix(v7): take user-configured gas-adjustment into account

- chain/cosmos/chain_node.go
- chainspec.go
- examples/cosmos/ethermint_test.go
- ibc/types.go
- local-interchain/go.mod
- local-interchain/rust/Cargo.lock
- local-interchain/rust/Cargo.toml
- local-interchain/rust/localic-std/Cargo.toml
- local-interchain/rust/main/Cargo.toml
for cosmos chains, ExposeAdditionalPorts takes a list of port ids that will be exposed on all validators and full nodes for the chains on random host ports.
extends the ethermint test by exposing the EVM & verifying the port actually gets exposed.
this is a backport of #1098 into the v7 branch.
> [BP v7 <- #1098] feat: add ExposeAdditionalPorts config option

- chain/cosmos/cosmos_chain.go
- chain/cosmos/ics.go
- examples/cosmos/chain_genesis_stake_test.go
- examples/cosmos/sdk_boundary_test.go
- examples/cosmwasm/rust-optimizer/rust_optimizer_test.go
- examples/cosmwasm/workspace-optimizer/workspace_optimizer_test.go
- examples/ibc/ics_test.go
- examples/ibc/wasm/wasm_ibc_test.go
- local-interchain/interchain/start.go
ref: https://github.com/strangelove-ventures/interchaintest/pull/1088#discussion_r1589636518
> test(ics): validate consumer transactions execute

- chain/cosmos/chain_node.go
- chain/cosmos/cosmos_chain.go
- chain/cosmos/ics.go
- I introduce helper lambda functions that trigger business logic before all nodes in a chain are started (`preStartNodes`), and a function called after a sidecar is started, but before the node is started (`preStartNode`)
- We use these methods in slinky, and would like to get off our [fork](https://github.com/skip-mev/slinky/blob/e369ddea9dff430f8f82c3865327ba6bde541abd/tests/integration/slinky_suite.go#L129)
> feat: adding functions for pre-start of node + pre-start of all nodes in a chain

- .github/workflows/unit-tests.yml
- examples/cosmos/sdk_boundary_test.go
- examples/ibc/ics_test.go
- interchain_test.go
- relayer/hermes/hermes_relayer.go
Allowing concurrent ops can result in `hermes create ...` commands failing because there's sequence numbers being modified by simultaneous commands. This PR adds per-chain locks that must be acquired to e.g. create a connection or channel
> fix(v7): prevent concurrent hermes operations on the same chain

- go.mod
- go.sum
Updates go-substrate-rpc-client dependency. Ibc-go team is removing DenomTrace and DenomTraces queries. Currently, they need to keep these types as deprecated for go-substrate-rpc-client which references them. https://github.com/cosmos/ibc-go/issues/6421 
We do not require nor use these queries so they were dropped.
> chore(deps): update go-substrate-rpc-client to remove the denom trace queries

- chain/cosmos/chain_node.go
- chain/internal/tendermint/tendermint_node.go
- dockerutil/file.go
- examples/cosmos/code_coverage_test.go
- ibc/types.go
closes: #1130
When testing in ICT, support code coverage output from the binary.
```go
ExternalGoCoverDir = "/tmp/my-app-coverage"
// before interchaintest.NewBuiltinChainFactory
cfgA.WithCodeCoverage()
// after test runs
t.Cleanup(func() {
dockerutil.CopyCoverageFromContainer(ctx, t, client, chain.GetNode().ContainerID(), chain.HomeDir(), ExternalGoCoverDir)
_ = ic.Close()
})
```
> feat: handle coverage from supported binaries

- chain/cosmos/chain_node.go
- chain/internal/tendermint/tendermint_node.go
ref: https://github.com/strangelove-ventures/interchaintest/pull/1157#discussion_r1659028598
> refactor: use `ReadFile` instead of `SingleFileContent`

- chain/cosmos/cosmos_chain.go
- chain/cosmos/ics.go
- ibc/types.go
This allows for more dynamic PreGenesis actions, in particular running custom commands on validators. Users should be aware that the chain they're receiving isn't started
> feat: PreGenesis now takes the chain instead of the chainconfig

- chain/cosmos/module_gov.go
- chain/cosmos/types.go
- examples/cosmos/chain_upgrade_ibc_test.go
There's no more `submit-proposal software-upgrade` command, so it has to go through a full proposal.json
> fix: upgrade proposals for SDK >= 0.47

- chain/cosmos/chain_node.go
- configuredChains.yaml
- examples/cosmos/chain_miscellaneous_test.go
- ibc/types.go
It's useful to just set "--gas auto" for all transactions. Right now, --gas auto will be set as the default for gaia chians.
> feat: Allow configuring default --gas limit for transactions.

- chain/cosmos/ics.go
IMO if we're manually overriding versions for the purposes of CCV transforms, we should honour whatever the user gave us as the version and not modify it.
> fix: keep Provider/ConsumerVerOverride from being wiped by ICS version

- chain/cosmos/chain_node.go
- chain/cosmos/sidecar.go
- dockerutil/fileretriever.go
- dockerutil/filewriter.go
- dockerutil/image.go
- dockerutil/kill.go
- dockerutil/setup.go
- dockerutil/strings.go
- dockerutil/volumeowner.go
- local-interchain/interchain/handlers/actions.go
- local-interchain/interchain/start.go
- local-interchain/rust/Cargo.lock
- local-interchain/rust/main/src/main.rs
- relayer/docker.go
Since local-ic was created, ctrl+c has been on the back burner for a year. It now properly cleans up a running instance.
`ict-` namespaces had to be added to containers so we don't kill non ict based networks. This MAY be breaking for some users of ICT if they hardcode expect values as hostnames. To fix, they would have to add `ict-` to the start of their container name.
This verification actually broke one of my rust test [here](https://github.com/strangelove-ventures/interchaintest/pull/1206/commits/a340c5256193e21689e1ca5cedb4c1b2457abdbe), but this is likely only due to internal verifications. I don't see why someone would do this outside of this repo.
- make install && local-ic start juno_ibc
- Wait some time (sometimes right away, sometimes delayed, someone after full start)
- run …
> feat(local-ic): catch os.Interrupt / sigterm signals and cleanup

- chain/cosmos/chain_node.go
- chain/cosmos/sidecar.go
- dockerutil/image.go
- dockerutil/kill.go
- dockerutil/strings.go
- local-interchain/rust/main/src/main.rs
- relayer/docker.go
closes #1212
The proper way to perform https://github.com/strangelove-ventures/interchaintest/pull/1206 (using hidden labels instead of name prefixes). Reverted back to previous formats, keeping the next release non api breaking)
Confirmed to work with relayers
> refactor: docker label cleanup for running containers

- .github/workflows/unit-tests.yml
- interchain_test.go
- relayer/hermes/hermes_relayer.go
Allowing them can result in "hermes create ..." commands failing because there's sequence numbers being modified by simultaneous commands.
BP of #1099
> fix: prevent concurrent hermes operations on the same chain

- .github/workflows/local-interchain.yaml
- local-interchain/bash/source.bash
- local-interchain/bash/test.bash
- local-interchain/interchain/handlers/actions.go
ref https://github.com/strangelove-ventures/interchaintest/issues/795
Basic external bash driver which can be imported to interact with local-ic. Why? it's easier sometimes and I find myself wanting a helper constantly.
---
> feat(local-ic): bash driver

- ibc/types.go
- local-interchain/interchain/handlers/chain_registry.go
- local-interchain/interchain/router/router.go
ref: https://github.com/rollchains/spawn/pull/194
if the chain_registry.json file is found when running `local-ic start <name>`, it will showcase this in an easy to query way. This makes it easy to connect wallets and build existing infra on top. Better UX
> feat: local chain registry endpoint

- chain/cosmos/module_slashing.go
- chain/cosmos/module_staking.go
the queries tend to reply with a nil result when they fail, so trying to access that result will cause a panic
> fix: error returns for queries in cosmos staking & slashing

- chain/cosmos/chain_node.go
- docs/envOptions.md
Manually overrides the logic to determine if a chain is running SDK 47 or greater.
> feat(v7): override sdk v47 version check with env variable

- ibc/relayer.go
- relayer/rly/cosmos_relayer.go
In order to create two different clients on chains you already have configured, you need to use the `--override` flag in the relayer. 
This PR adds the ability to take advantage this `--override` flag with interchaintest.
Note that this is only implemented for the go relayer.
> feat: implement override flag when creating clients

- dockerutil/container_lifecycle.go
- examples/cosmos/bad_genesis_params_test.go
- local-interchain/interchain/start.go
closes https://github.com/strangelove-ventures/interchaintest/issues/1238
This is a huge user experience improvement for ICT & local-ic upon a bad genesis param set (or some other failed startup option). 
Before, the network would hang and just state it failed to query
:
failed to start chains: failed to start chain localosmosis-1: All attempts fail:
`#1`: post failed: Post \"http://0.0.0.0:26659\": dial tcp 0.0.0.0:26659: connect: connection refused
...
`#30` ...
This chain uses a genesis modification of `{"key": "app_state.gov.params.voting_period", "value": "bad"},`. Both validators show this error in an easy to read format + the docker logs for the stacktrace.
> feat: check for panic in logs on start

- chain/cosmos/module_staking.go
Related to Issue [#1261](https://github.com/strangelove-ventures/interchaintest/issues/1261)
This fix avoids reusing the same object during each iteration of the loop, preventing all elements in delegations from pointing to the same "d".
> fix(query): StakingQueryDelegationsTo reusing the same object

- chain/thorchain/sidecar.go
- chain/utxo/cli.go
- chain/utxo/utxo_chain.go
- chain/utxo/wallet.go
- examples/thorchain/setup_test.go
- examples/utxo/start_test.go
- local-interchain/chains/state/README.md
Fixes a few race conditions on thorchain and utxo chains.
Thorchain: sidecar processes now get their own copy of env list so they can make runtime changes in parallel.
Utxo: reading and writing KeynameToWalletMap and AddrToKeynameMap is now protected by a mutex. The block producing go routine is now ran after faucet creation and a utxo stop method is added for the test framework to cancel its context.
Thorchain's setup_test.go is updated to call the utxo chain's stop method. This will also be reflected in the thornode v50 branch.
> fix(thorchain/utxo): fix race conditions

- local-interchain/Makefile
ref: https://github.com/rollchains/spawn/issues/248
> fix: MacOS strip debug info for proper runs

- local-interchain/README.md
- local-interchain/interchain/config.go
- local-interchain/interchain/types/types.go
> feat: add `AdditionalStartArgs` and `Env` to localic cfg

- docs/ciTests.md
The link check failed in #1296. It isn't related to the PR.
> fix: remove the version to avoid the link check

- .codespellrc
- chain/cosmos/chain_node.go
- chain/cosmos/sidecar.go
- chain/ethereum/ethererum_chain.go
- chain/internal/tendermint/tendermint_node.go
- chain/namada/namada_chain.go
- chain/namada/namada_node.go
- chain/namada/wallet.go
- chain/penumbra/penumbra_app_node.go
- chain/penumbra/penumbra_client_node.go
- chain/polkadot/parachain_node.go
- chain/polkadot/relay_chain_node.go
- chain/thorchain/sidecar.go
- chain/thorchain/thornode.go
- chain/utxo/utxo_chain.go
- chainfactory.go
- chainspec.go
- configuredChains.yaml
- dockerutil/container_lifecycle.go
- dockerutil/setup.go
- examples/namada/namada_chain_test.go
- go.mod
- go.sum
- ibc/types.go
- interchain.go
- relayer/docker.go
- relayer/hermes/hermes_config.go
- relayer/hermes/hermes_relayer.go
To support [Namada](https://namada.net/) test,
- Add Namada bootstrapping under `chain/namada`
- Enable to specify an IP address for a node
- It would be great if you had a better way to create docker network
- Change Hermes config to set the chain type
- Add the example test: `examples/namada/namada_chain_test.go`
> feat(namada): Support Namada test

- chain/namada/namada_node.go
Sorry for the mess. I didn't merge this fix to #1296.
Chainging the config wasn't required and it always failed.
> fix(namada): Remove unnecesary namada config

- chain/ethereum/foundry/anvil_chain.go
- chain/ethereum/foundry/forge.go
- chain/ethereum/geth/geth_chain.go
- chain/thorchain/api_query.go
- chain/thorchain/module_thorchain.go
- chain/thorchain/thorchain.go
- chain/thorchain/types.go
- go.mod
- go.sum
- local-interchain/go.mod
- local-interchain/go.sum
Currently, in order to use bifrost, thorchain must be started at genesis with a single validator. Churns occur every 60 blocks, so it will take at most ~2 minutes to update the validator set. This PR adds the ability to easily add validators to thorchain's network. It also adds support for duplicating a validator, in our case, to test double sign slashing.
This PR also fixes a possible race condition in ethereum-based chains.
> feat(thorchain): add support for adding/duplicating validators

- chain/namada/namada_chain.go
- chain/namada/namada_node.go
- examples/namada/namada_chain_test.go
Namada v1.0.0 has been released. I'd like to update the example and fix a bug for a full node.
- Update Namada test example
- Update Namada to v1.0.0
- Update Hermes to use the upstream version
- Fix the spent gas
- Fix for a full node to be able to access via RPC
> fix(namada): Update Namada example test with Namada v1.0.0
