README.md

Completes https://github.com/strangelove-ventures/ibc-test-framework/issues/49

docs: Add test focus examples to README

---

LICENSE

Add Apache2 license

---

chain/penumbra/penumbra_chain.go

Concurrent goroutines cannot append to the same slice, but they can
write to predetermined indices in an existing slice.

Fix data race in penumbra chain setup

---

chain/cosmos/cosmos_chain.go
chain/cosmos/query.go
chain/penumbra/penumbra_chain.go
conformance/test.go
ibc/chain.go
ibc/packet.go
ibc/packet_test.go
test/poll_for_state.go
test/poll_for_state_test.go

Finishes:
* https://github.com/strangelove-ventures/ibctest/issues/82
* https://github.com/strangelove-ventures/ibctest/issues/83
* One more method for ibc.Chain interface.

feat: Poll for timeouts

---

internal/blockdb/tui/update_test.go

Fix ineffectual assignment

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go

As surfaced in https://github.com/strangelove-ventures/ibctest/pull/173

fix: Minor fixes to cosmos implementation

---

chain/cosmos/chain_node.go

I don't think anything in ibctest exercises this, but it looks like it
should work as intended.
For #200.

Use docker API to copy cosmos contract into docker volume

---

internal/dockerutil/setup.go

There are occasional errors about a prune already being in progress
(likely due to other tests executing concurrently), so retry on that
particular error.

Retry pruning volumes on cleanup

---

chain/cosmos/cosmos_chain.go
chain/penumbra/penumbra_app_node.go
chain/penumbra/penumbra_chain.go
chain/penumbra/penumbra_chain_test.go
examples/packet_forward_test.go
ibc/chain.go

Cleanup no longer required since the permissions issue is gone now with the docker volumes integration

Remove Chain Cleanup

---

chain/polkadot/parachain_node.go
chain/polkadot/relay_chain_node.go

Phase 3 of #67 
Polkadot chains are composed of the relay chain (polkadot chain) nodes and the parachain nodes for involved parachains (e.g. Composable). This brings in the parachain node docker orchestration methods.

Polkadot parachain node

---

chain/polkadot/parachain_node.go
chain/polkadot/polkadot_chain.go
chain/polkadot/relay_chain_node.go
go.mod
go.sum
ibc/chain.go

Phase 4 of #67
Adds the `PolkadotChain` `ibc.Chain` implementation.
Currently supported:
- Start chain
- Fetch height
The next PR will include wiring up the `PolkadotChain` in the `ChainFactory` and `ChainSpec`, and adding the `PolkadotChain` test

Add PolkadotChain

---

interchain.go

Clarify comment as trillions of units.

---

interchain_test.go

updated matcher

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
chain/penumbra/penumbra_chain.go
chain/polkadot/polkadot_chain.go
chainfactory.go
chainset.go
chainspec.go
examples/upgrade_test.go
go.mod
go.sum
ibc/chain.go
ibc/tx.go
ibc/types.go

Adds a public method for importing into integration tests, `CosmosChainUpgradeTest`. Adds CI test for a known working chain upgrade juno v6 to v7.
Chain upgrade procedure:
- Start chain
- Submit software upgrade proposal
- Vote yes from all validators
- Wait for voting period to expire
- Wait for chain to halt
- Shutdown all nodes
- Upgrade version on all nodes
- Start all nodes back up
- Wait for chain to produce blocks

Upgrade test example

---

chain/polkadot/polkadot_chain.go

This PR closes #258 
...
- Open page ...
- Click ...
- Make sure that ...
-  #258 
- build passing [here](https://github.com/cosmos/ibc-go/runs/7994448537?check_suite_focus=true)
- ...
- ...
- ...
- ...

fix arm build

---

chain/cosmos/chain_node.go
chain/polkadot/polkadot_chain.go
conformance/relayersetup.go
examples/interchain_queries_test.go
go.mod
go.sum
ibc/relayer.go
interchain.go
internal/blockdb/messages_view_test.go
relayer/docker.go
relayer/rly/cosmos_relayer.go

This PR adds an example test case for the packet ICQ implementation.
https://github.com/quasar-finance/interchain-query-demo

Add ICQ test case

---

chain/cosmos/cosmos_chain.go
chain/penumbra/penumbra_chain.go
chain/polkadot/polkadot_chain.go
ibc/chain.go

This PR removes the ICA related functions from the `Chain` interface.

Remove ICA functions from chain interface

---

chain/cosmos/chain_node.go

`applyConfigChanges` was unused in the project. Not sure how this made it past the original CI linter.

Remove Unused Funtion

---

chain/internal/tendermint/tendermint_node.go

heighliner tendermint images no longer have `sed` and this was a dirty hack anyways

Remove sed command calls from tendermint node

---

chain/internal/tendermint/tendermint_node.go

v3 tm sed fix

---

examples/osmosis/cosmos_chain_gamm_pool_test.go

[v3] gamm pools create, swap, ibc test

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
chain/cosmos/osmosis.go
chain/cosmos/poll.go
chain/cosmos/types.go
examples/cosmos_chain_upgrade_ibc_test.go
examples/cosmos_chain_upgrade_test.go
ibc/tx.go
ibc/types.go
test/poll_for_state.go

Cherry pick from v3. did v3 first for this one since it was applicable to the osmosis tests on v3, but can also be added to main.

[v5] Proposal Polling and Pools

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
cmd/ibctest/ibctest_test.go
examples/cosmos_chain_upgrade_ibc_test.go
examples/interchain_queries_test.go
examples/packet_forward_test.go
ibc/relayer.go
interchain.go
interchain_test.go
relayer/docker.go
relayer/rly/cosmos_relayer.go
test_user.go

[v3] updates for v2.1.0

---

conformance/flush.go
ibc/relayer.go
ibc/types.go
internal/blockdb/messages_view_test.go
relayer/docker.go
relayer/rly/cosmos_relayer.go

Adds interface method for updating a path's channel filter

ibc.Relayer UpdatePath

---

relayer/rly/cosmos_relayer.go

https://github.com/cosmos/relayer/releases/tag/v2.1.2

Update rly to v2.1.2

---

chainfactory.go
examples/polkadot/polkadot_chain_test.go

Composable is now using nix to build their stack.
https://github.com/strangelove-ventures/heighliner/pull/42

Updates for nix

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go

Split InstantiateContract into StoreContract and InstantiantContract 
Fix the store contract ExecTx call
Add QueryContract
...
- Open page ...
- Click ...
- Make sure that ...
- ...
- ...
- ...
- ...
- ...
- ...

Port contract function changes to v6/main from v3

---

relayer/rly/cosmos_relayer.go

Expose const for rly default uid:gid

---

chain/cosmos/chain_node.go
chainspec.go
ibc/relayer.go
ibc/types.go
interchain.go
relayer/docker.go
relayer/rly/cosmos_relayer.go

Cherry picks #338 into the `V3` branch.

Cherry Pick: Integrate coin-type configuration (#338)

---

relayer/docker.go

Cherry-pick of #349 
* Use relayer home dir in slim rly image
* Remove requirement for chown in rly image

[v6] Changes for slim rly images

---

relayer/docker.go

Cherry-pick of https://github.com/strangelove-ventures/ibctest/pull/349
- Use relayer home dir in slim rly image
- Remove requirement for chown in rly image

[v3] Changes for slim rly images 

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
chain/cosmos/types.go
examples/cosmos/chain_param_change_test.go
examples/cosmos/params/IncreaseValidatorsParam.json
go.mod

Backport from #467 to v3 branch
(for Noble e2e param testing)

[v3] ParamChangeProposal

---

chain/cosmos/broadcaster.go
chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go

- Make public 2 functions: `GenesisFileContent` and `OverwriteGenesisFile`

Make function public

---

chain/cosmos/cosmos_chain.go
chain/penumbra/penumbra_chain.go
chain/polkadot/polkadot_chain.go
go.mod
go.sum
internal/dockerutil/container_lifecycle.go
internal/dockerutil/fileretriever_test.go
internal/dockerutil/filewriter_test.go
internal/dockerutil/image.go
internal/dockerutil/setup.go
internal/dockerutil/setup_test.go
relayer/docker.go

Big bump for docker.
`v20.10.19` to `v24.0.1`

Bump docker dependency 

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
chain/cosmos/sidecar.go
ibc/types.go

With these minor modification, the sidecars are working great for horcrux https://github.com/strangelove-ventures/horcrux/pull/174

Sidecar home dir and host ports

---

configuredChains.yaml

Adding ics-provider config to enable usage of ics images on heighliner.

add ics-provider config

---

.github/mergify.yml

Oops, I missed this in: https://github.com/strangelove-ventures/interchaintest/pull/735

Fix backport

---

.github/workflows/e2e-tests.yml
.github/workflows/unit-tests.yml

issues with self hosting due to K8, removed test should let us do this again

gh runners: ubuntu-latest

---

local-interchain/cmd/local-ic/interaction.go
local-interchain/cmd/local-ic/new_chain.go
local-interchain/cmd/local-ic/start_chain.go
local-interchain/go.mod
local-interchain/interchain/config.go
local-interchain/interchain/genesis.go
local-interchain/interchain/handlers/actions.go
local-interchain/interchain/handlers/info.go
local-interchain/interchain/handlers/uploader.go
local-interchain/interchain/ibc.go
local-interchain/interchain/logs.go
local-interchain/interchain/router/router.go
local-interchain/interchain/start.go

required so https://github.com/rollchains/spawn/issues/112 could integrate

fix: local-ic go namespace

---

local-interchain/Makefile
local-interchain/cmd/local-ic/main.go

title. required to spawn update notifications UX

feat(local-ic): add version cmd

---

Dockerfile.local-interchain
docker-compose.yml
go.sum
local-interchain/go.mod
local-interchain/go.sum

As requested at Devmos from Michael Sofaer (doing it without DIND, just grabbing host socket instance)
also ref #1140 as the network host mode for GitLab CI could the issue there

feat(local-interchain): docker compose

---

chain/cosmos/cosmos_chain.go
chain/cosmos/ics.go
docs/envOptions.md
examples/ibc/ics_test.go
go.mod
go.sum
ibc/types.go
local-interchain/go.mod
local-interchain/go.sum

This reflects how ICS chains are launched in the wild, with validators setting their consensus keys before the chain launches

feat: allow consumers to have different keys than providers

---

chain/cosmos/cosmos_chain.go
chain/cosmos/ics.go
docs/envOptions.md
examples/ibc/ics_test.go
go.mod
go.sum
ibc/types.go
local-interchain/go.mod
local-interchain/go.sum

I ended up needing this backport, so I did it myself 😄 It's the same as #1179 but i fixed the proposals query. I figure there won't be hundreds of proposals in a test case (??) so hopefully we don't have to worry about pagination

feat: allow consumers to have different keys than providers (#1175)

---

chain/cosmos/chain_node.go
chain/cosmos/cosmos_chain.go
examples/cosmos/chain_miscellaneous_test.go
ibc/types.go

Fixes: gas rounding issue from https://github.com/strangelove-ventures/interchaintest/pull/747#discussion_r1320159263
Adds `gas` to ChainConfig.
Updates TxCommand to auto set `gas`.

fix: tx out of gas

---

local-interchain/interchain/start.go

Allows any origin for localhost to interact with the local-ic instance
Issue encountered by @marslavish

fix: local-ic cors
